spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/resources/
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 80
